const locationsOffline = [
    {
        id: 0,
        location: "Damascus",
        country: "Syria",
        geoLoc: {lat: 33.513229131401154, lon: 36.276832308243854},
        period: {start: "2043-02-23", end: "2043-02-25"},
        places: [{lat: 33.511373686074556, lon: 36.30689980504887}],
        thumbnail: {thumb: "travelBlog_Damascus_01_thumb.jpg",
                    alt: "grainy high contrast monochrome rendering of the Umayyad Mosque in Damascus"},
        images: ["travelBlog_Damascus_01.jpg",
                "travelBlog_Damascus_02.jpg",
                "travelBlog_Damascus_03.jpg",
                "travelBlog_Damascus_04.jpg"],
        altImages:  ["grainy high contrast monochrome rendering of the Umayyad Mosque in Damascus",
                    "grainy high contrast monochrome rendering of the inner courtyard of Umayyad Mosque in Damascus",
                    "grainy high contrast monochrome rendering of the inner courtyard of Umayyad Mosque in Damascus",
                    "grainy high contrast monochrome rendering of the Umayyad Mosque in Damascus"],
        credits: ["3D model by MiniWorld3D <a href='https://www.printables.com/model/519393-great-mosque-of-damascus-syria/files' target='_blank'>[printables]</a>"],
        reason: "Syria is one of the 10 countries most affected by the man made climate change.",
        textBody: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Maiores a qui exercitationem velit omnis ullam nemo? Corporis modi eum non culpa deserunt, animi tenetur perspiciatis eos unde similique qui sequi accusamus. Dolorem, eligendi molestiae. Aliquam, eum velit accusamus fuga aliquid et ex tenetur quisquam numquam labore soluta, deleniti aut necessitatibus impedit dolorem! Debitis nulla harum dolorem animi? Repellendus architecto sapiente ex deserunt ea quia nobis quos cum. Ducimus aspernatur ab dignissimos soluta alias reiciendis eius enim ipsum earum provident distinctio incidunt, pariatur qui odit voluptate quidem ipsam, error magni vel. Debitis deleniti asperiores quasi harum unde optio, facere eum quaerat.",
        suggested: false
    },
    {
        id: 1,
        location: "Paris",
        country: "France",
        geoLoc: {lat: 48.85754657470296, lon: 2.3513719627048615},
        period: {start: "2058-06-07", end: "2058-06-07"},
        places: [{lat: 48.85826370182144, lon: 2.294501153650173}],
        thumbnail:  {thumb: "travelBlog_Paris_01_thumb.jpg",
                    alt: "grainy monochrome rendering of the Eiffel Tower"},
        images: ["travelBlog_Paris_01.jpg",
                "travelBlog_Paris_02.jpg",
                "travelBlog_Paris_03.jpg",
                "travelBlog_Paris_04.jpg"],
        altImages:  ["grainy monochrome rendering of the Eiffel Tower",
                    "grainy monochrome rendering of the Eiffel Tower",
                    "grainy monochrome rendering of the Eiffel Tower",
                    "grainy monochrome rendering of the Eiffel Tower"],
        credits: ["3D model by AdrienJ <a href='https://www.turbosquid.com/3d-models/eiffel-tower-3d-model-1940053' target='_blank'>[turbosquid]</a>"],
        reason: "Paris is the most dense city in europe, learnings from here can be applied in multiple european cities.",
        textBody: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem perferendis dolor numquam similique adipisci odit? Quo ducimus quia alias quisquam omnis? Mollitia quo quia, recusandae deserunt repellat impedit consequatur quae!",
        suggested: false
    },
    {
        id: 2,
        location: "Abuja",
        country: "Nigeria",
        geoLoc: {lat: 9.056272572547446, lon: 7.4985246666398915},
        period: {start: "2064-12-15", end: "2064-12-16"},
        places: [{lat: 9.06026540993329, lon: 7.4898644477909695}],
        thumbnail:  {thumb: "travelBlog_Abuja_01_thumb.jpg",
                    alt: "grainy monochrome rendering of the Abuja National Mosque in Abuja"},
        images: ["travelBlog_Abuja_01.jpg",
                "travelBlog_Abuja_02.jpg",
                "travelBlog_Abuja_03.jpg",
                "travelBlog_Abuja_04.jpg"],
        altImages:  ["grainy monochrome rendering of the Abuja National Mosque in Abuja",
                    "grainy monochrome rendering of the Abuja National Mosque in Abuja",
                    "grainy monochrome rendering of the Abuja National Mosque in Abuja",
                    "grainy monochrome rendering of the Abuja National Mosque in Abuja"],
        credits: ["3D model by MiniWorld3d <a href='https://www.printables.com/model/664805-abuja-national-mosque-nigeria/files' target='_blank'>[printables]</a>"],
        reason: "Nigeria is one of the 10 countries most affected by the man made climate change.",
        textBody: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem perferendis dolor numquam similique adipisci odit? Quo ducimus quia alias quisquam omnis? Mollitia quo quia, recusandae deserunt repellat impedit consequatur quae!",
        suggested: false
    },
    {
        id: 3,
        location: "Berlin",
        country: "Germany",
        geoLoc: {lat: 52.52000587310054,lon: 13.404946669381067},
        period: {start: "2084-04-13", end: "2084-04-17"},
        places: [{lat:52.51628214532544, lon: 13.377727090554865}],
        thumbnail:  {thumb: "travelBlog_Berlin_01_thumb.jpg",
                    alt: "grainy high contrast monochrome rendering of the Brandenburg Gate in Berlin"},
        images: ["travelBlog_Berlin_01.jpg",
                "travelBlog_Berlin_02.jpg",
                "travelBlog_Berlin_03.jpg",
                "travelBlog_Berlin_04.jpg"],
        altImages:  ["grainy high contrast monochrome rendering of the Brandenburg Gate in Berlin",
                    "grainy high contrast monochrome rendering of the Brandenburg Gate in Berlin",
                    "grainy high contrast monochrome rendering of the Brandenburg Gate in Berlin",
                    "grainy high contrast monochrome rendering of the Brandenburg Gate in Berlin"],
        credits: ["3D model by jo2bigornia <a href='https://www.turbosquid.com/3d-models/free-max-mode-berlin-gate/675373' target='_blank'>[turbosquid]</a>"],
        reason: "Berlin will mainly face more heat waves and droughts in the future.",
        textBody: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem perferendis dolor numquam similique adipisci odit? Quo ducimus quia alias quisquam omnis? Mollitia quo quia, recusandae deserunt repellat impedit consequatur quae!",
        suggested: false
    }
]